import React from "react";
import { Box, Heading, Text, Image, Flex, useBreakpointValue } from "@chakra-ui/react";

const Poster = require("../images/zero-emissions-road-sign-message-160843165.webp");
const FootPrints = require("../images/carbon-footprint.jpg");
const WhyEcosavvy = require("../images/new.jpg");

const HomePage = () => {
  // Use useBreakpointValue to handle different screen sizes
  const imageSize = useBreakpointValue({ base: "200px", md: "300px", lg: "500px" });

  return (
    <>
      <Box
        px={{ base: 4, md: 8, lg: 20 }}
        py={{ base: 6, md: 10 }}
        fontSize="large"
        backgroundColor="gray.700"
        color="white"
      >
        {/* Welcome Section */}
        <Box textAlign="center" mb={{ base: 6, md: 8 }} p={4} bg="gray.800" borderRadius="md">
          <Heading as="h1" size="2xl" mb={4} color="white">
            Welcome
          </Heading>
          <Text fontSize={{ base: "md", md: "lg" }} color="white">
            Step into a Sustainable Future with Us!
          </Text>
        </Box>

        {/* Image with Heading and Text */}
        <Flex direction={{ base: "column", md: "row" }} align="center" mb={{ base: 6, md: 8 }} gap={8}>
          <Box flex={{ base: 1, md: 1 }}>
            <Image
              src={Poster}
              alt="Landscape"
              maxW="100%"
              height={imageSize}
              objectFit="cover"
              borderRadius="md"
              boxShadow="md"
            />
          </Box>
          <Box flex={{ base: 1, md: 1 }} textAlign={{ base: "center", md: "left" }}>
            <Heading as="h2" size="lg" mb={4}>
              Our Mission
            </Heading>
            <Text>
              We are dedicated to creating innovative solutions to manage carbon emissions and promote sustainability. Our platform provides comprehensive tools for understanding and reducing your carbon footprint, helping you achieve environmental goals effectively.
            </Text>
          </Box>
        </Flex>

        {/* Introduction Paragraph */}
        <Text mb={{ base: 4, md: 6 }} lineHeight="tall" textAlign="justify">
          In the face of growing environmental concerns and stringent regulatory demands, Indian coal mines are increasingly seeking innovative solutions to manage their carbon emissions and pursue sustainability goals. Our web application is specifically designed to address these needs by providing a comprehensive platform for quantifying carbon footprints and exploring pathways to carbon neutrality. By integrating advanced data analytics with user-friendly interfaces, this application enables coal mines to accurately measure their emissions, track progress in real-time, and evaluate various strategies for reducing their carbon impact. With tailored features for emission tracking, scenario modeling, and regulatory reporting, our solution empowers mines to take meaningful steps towards environmental stewardship while aligning with global sustainability targets.
        </Text>

        {/* What is Carbon Footprint Section */}
        <Box mb={{ base: 6, md: 8 }} display={{ base: "block", md: "flex" }} alignItems="center" gap={{ base: 4, md: 8 }}>
          <Box flex={{ base: 1, md: 1 }} mb={{ base: 6, md: 0 }}>
            <Heading as="h2" size="lg" mb={4} textAlign="center">
              Hmm.. I'm not sure about what Carbon Footprints are 🤔
            </Heading>
            <Text textAlign="center">
              A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. The average carbon footprint for a person in the United States is 16 tons, one of the highest rates in the world. Globally, the average carbon footprint is closer to 4 tons. To have the best chance of avoiding a 2℃ rise in global temperatures, the average global carbon footprint per year needs to drop to under 2 tons by 2050. Lowering individual carbon footprints from 16 tons to 2 tons doesn’t happen overnight! By making small changes to our actions, like eating less meat, taking fewer connecting flights, and line drying our clothes, we can start making a big difference.
            </Text>
          </Box>
          <Box flex={{ base: 1, md: 1 }} textAlign="center">
            <Image
              src={FootPrints}
              alt="What is Carbon Footprint"
              maxW="100%"
              borderRadius="md"
              boxShadow="md"
            />
          </Box>
        </Box>

        {/* Why Choose Us Section */}
        <Box mb={{ base: 6, md: 8 }} display={{ base: "block", md: "flex" }} alignItems="center">
          <Box flex={{ base: 1, md: 1 }} textAlign="center">
            <Image
              src={WhyEcosavvy}
              alt="Why Choose Us"
              maxW="100%"
              borderRadius="md"
              boxShadow="md"
            />
          </Box>
          <Box flex={{ base: 1, md: 1 }} ml={{ base: 0, md: 4 }} textAlign="center">
            <Heading as="h2" size="lg" mb={4}>
              About Our Platform
            </Heading>
            <Text>
              Our website stands out as the premier choice for Indian coal mines seeking to reduce their carbon footprint and achieve sustainability. We offer specialized tools and localized insights tailored specifically for the coal mining industry, providing a comprehensive carbon footprint calculator that considers energy consumption, fuel usage, and methane emissions. Our user-friendly interface ensures a seamless experience across all devices, while our commitment to data security, educational resources, and expert support guarantees you have everything you need to make informed, effective decisions. By choosing our platform, you benefit from a cost-effective, scalable solution designed to help you stay ahead of industry regulations and contribute to a greener future.
            </Text>
          </Box>
        </Box>
      </Box>

      <Box
        backgroundColor="white"
        color="green.700"
        py={4}
        textAlign="center"
        fontWeight="bold"
        boxShadow="sm"
      >
        Made with 💚 Go Green ©ClimateCrew
      </Box>
    </>
  );
};

export default HomePage;
